# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_addresses', '0001_initial'),
        ('posts', '0007_auto_20180211_2036'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('status', models.CharField(choices=[(b'approved', 'Approved'), (b'pending', 'Pending'), (b'refunded', 'Refunded'), (b'shipped', 'Approved')], default=b'approved', max_length=20)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_autor', to=settings.AUTH_USER_MODEL, verbose_name='AUTOR_LABEL')),
                ('billing_addresss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_billing_addresss', to='user_addresses.Addresess', verbose_name='BILLING_LABEL')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_payment_method', to='payments.PaymentMethod', verbose_name='SHIPPING_LABEL')),
                ('shipping_addresss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_shipping_addresss', to='user_addresses.Addresess', verbose_name='SHIPPING_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'DISCOUNTS_TITLE_PLURAL',
                'db_table': 'orders',
                'verbose_name': 'DISCOUNTS_TITLE',
            },
        ),
        migrations.CreateModel(
            name='OrderShippingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('price', models.CharField(blank=True, max_length=20)),
                ('qty', models.IntegerField(blank=True, default=0)),
                ('carrier', models.CharField(choices=[(b'USPS', 'USPS'), (b'FEDEX', 'FEDEX'), (b'DHL', 'DHL'), (b'MRW', 'MRW'), (b'ZOOM', 'ZOOM')], default=b'USPS', max_length=20)),
                ('tracking_number', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_items_shipping_related_order', to='orders.Orders', verbose_name='AUTOR_LABEL')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_items_shipping_related_product', to='posts.PostItem', verbose_name='AUTOR_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'SHIPPING_TITLE_PLURAL',
                'db_table': 'orders_items',
                'verbose_name': 'SHIPPING_TITLE',
            },
        ),
    ]
