# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingitem',
            name='carrier',
            field=models.CharField(choices=[(b'USPS', 'USPS'), (b'FEDEX', 'FEDEX'), (b'DHL', 'DHL'), (b'MRW', 'MRW'), (b'ZOOM', 'ZOOM'), (b'PERSONAL_DELIVERY', 'PERSONAL DELIVERY'), (b'EMPTY', 'EMPTY')], default=b'EMPTY', max_length=20),
        ),
    ]
