# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_postitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='TITLE_LABEL')),
                ('percent', models.FloatField(blank=True, max_length=255, verbose_name='PERCENTAJE_LABEL')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='STAR_DATE_LABEL')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='END_DATE_LABEL')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_item_autor', to='posts.PostItem', verbose_name='AUTOR_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'DISCOUNTS_TITLE_PLURAL',
                'db_table': 'product_discounts',
                'verbose_name': 'DISCOUNTS_TITLE',
            },
        ),
    ]
