# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='SLUG_LABEL'),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='SLUG_LABEL'),
        ),
    ]
