# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180207_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('archetype', models.CharField(choices=[(b'choices', b'Choices'), (b'text', b'Text'), (b'selectable', b'Selectable'), (b'date', b'Date')], default=b'text', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='NAME_LABEL')),
                ('priceable', models.BooleanField(default=True, verbose_name='PRICEABLE_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'ATTRIBUTES_TITLE_PLURAL',
                'db_table': 'attributes',
                'verbose_name': 'ATTRIBUTES_TITLE',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='THUNBNAIL_LABEL')),
                ('thumbnail_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='ATL_TEXT_LABEL')),
                ('featured_image', models.TextField(blank=True, null=True, verbose_name='FEATURED_IMAGE_LABEL')),
                ('featured_image_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='ATL_TEXT_LABEL')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='NAME_LABEL')),
                ('price', models.FloatField(verbose_name='NAME_LABEL')),
                ('attributes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_product_attributes_related_attributes', to='posts.Attributes', verbose_name='ATTRIBUTES_LABEL')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_product_attributes_related_product', to='posts.PostItem', verbose_name='PRODUCT_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'PRODUCT_ATTRIBUTES_TITLE_PLURAL',
                'db_table': 'posts_product_attributes',
                'verbose_name': 'PRODUCT_ATTRIBUTES_TITLE',
            },
        ),
    ]
