# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180212_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershippingitem',
            name='variant_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[(b'approved', 'Approved'), (b'pending', 'Pending'), (b'refunded', 'Refunded'), (b'processed', 'Processed')], default=b'approved', max_length=20),
        ),
    ]
