# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180212_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('key', models.CharField(max_length=255, verbose_name='KEY_LABEL')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='VALUE_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'PAYMENT_METHOD_TITLE_PLURAL',
                'db_table': 'payment_methods_fields',
                'verbose_name': 'PAYMENT_METHOD_TITLE',
            },
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='city',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='country',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method',
            field=models.CharField(blank=True, choices=[(b'paypal', 'Paypal'), (b'mercadopago', 'Mercadopago'), (b'stripe', 'Stripe'), (b'bank_transfer', 'Bank transfer')], max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethodfields',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentMethod', verbose_name='AUTOR_LABEL'),
        ),
    ]
