# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
            ],
            options={
                'ordering': ('-creation_date',),
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('cart',),
                'db_table': 'cart_addresses',
                'verbose_name': 'Cart Address',
                'verbose_name_plural': 'Cart Addresses',
            },
        ),
        migrations.CreateModel(
            name='CartPaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.TextField(blank=True, max_length=10, null=True, verbose_name='Payment Type')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='cart')),
            ],
            options={
                'ordering': ('cart',),
                'db_table': 'cart_payment_type',
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('unit_price', models.FloatField(verbose_name='unit price')),
                ('object_id', models.PositiveIntegerField()),
                ('variant_id', models.PositiveIntegerField(null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('cart',),
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_key', models.TextField(blank=True, max_length=255, null=True, verbose_name='Attribute Key')),
                ('attribute_value', models.TextField(blank=True, max_length=255, null=True, verbose_name='Attribute Value')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Item', verbose_name='item')),
            ],
            options={
                'ordering': ('item',),
                'db_table': 'cart_item_attributes',
                'verbose_name': 'Item Attribute',
                'verbose_name_plural': 'Item Attributes',
            },
        ),
    ]
