# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaddresses',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartaddresses',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartpaymenttype',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='itemattributes',
            name='item',
        ),
        migrations.DeleteModel(
            name='CartAddresses',
        ),
        migrations.DeleteModel(
            name='CartPaymentType',
        ),
        migrations.DeleteModel(
            name='ItemAttributes',
        ),
    ]
