# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180212_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='PAYMENT_DATE_LABEL'),
            preserve_default=False,
        ),
    ]
