# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_LABEL')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='MODIFIED_LABEL')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='TITLE_LABEL')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('percent', models.FloatField(blank=True, max_length=255, verbose_name='PERCENTAJE_LABEL')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ('-id',),
                'verbose_name_plural': 'DISCOUNTS_TITLE_PLURAL',
                'db_table': 'taxes',
                'verbose_name': 'DISCOUNTS_TITLE',
            },
        ),
    ]
