# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
        ('posts', '0002_postitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='post_item_related_taxes', to='taxes.Taxes', verbose_name='TAXES_TITLE_PLURAL'),
        ),
    ]
