# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_attributes_productattributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='price',
            field=models.FloatField(blank=True, verbose_name='NAME_LABEL'),
        ),
    ]
