
INSTALLED_APPS = (
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'django_countries',
    'rest_framework',
    'rest_framework.authtoken',
    'django_markup',
    'captcha',
    'widget_tweaks',
    'mptt',
    'user',
    'rss',
    'sitemap',
    'utilities',   
    'globaly',   
    'posts',
    'user_addresses',
    'taxes',
    'orders',
    'media',
    'discount',
    'navigation',
    'comments',   

)
